### ISSUE TITLE
list-deployments output isn't shown as table

### ISSUE THREAD

**Issue by ganeshnj** [aws/aws-dotnet-deploy#162]
**Describe the bug**
list-deployments output isn't shown as table like any other list result such as `List-ChildItem` where a customer can select particular column and process the output.

**To Reproduce**
1. Make sure there exists deployments
2. `dotnet aws list-deployments | Select-Object "Cloud Applications:"`
3. Observer it doesn't select the  "Cloud Applications:" column

**Logs**
Logs obtained from CLI output.

**Expected behavior**
`dotnet aws list-deployments | Select-Object "Cloud Applications:"` should only list the deployments column.

Similar to `Get-ChildItem | Select-Object Name`.

**Screenshots**
![image](https://user-images.githubusercontent.com/8882380/111560396-995b5d80-874f-11eb-897b-b186de2154e9.png)

**Screen recording**
N/A

**Environment (please complete the following information):**
 - CLI Version: [eg. 1.0.0]  0.4.2
 - Include the output of `dotnet --info`
 - OS Info:  Windows 10

**Additional context**

---

This is a :bug: bug report

**Comment by ashishdhingra** [comment]
Reproducible.

- Follow the instructions at https://aws.github.io/aws-dotnet-deploy/docs/getting-started/run-tool/ to deploy sample application using command `dotnet aws deploy --profile default --region us-east-1`.
- Verify that the application is listed as a result of the command `dotnet aws list-deployments --profile default --region us-east-1`.
```
AWS .NET deployment tool for deploying .NET Core applications to AWS.
Project Home: https://github.com/aws/aws-dotnet-deploy

Configuring AWS Credentials from Profile default.
Configuring AWS region with specified value us-east-1.

Cloud Applications:
-------------------
HelloWorld (CloudFormation Stack)
```
- Run the command in PowerShell terminal `dotnet aws list-deployments --profile default --region us-east-1 | Select-Object "Cloud Applications:"`. It doesn't return anything:
```

Cloud Applications:
-------------------
```

Unsure if this is a valid issue since the output of `dotnet aws list-deployments` is not an object, but a logging output. For instance, if we run the command `dotnet aws list-deployments --profile default --region us-east-1 | Select-Object *`, it returns:
```
Length
------
    69
    54
     0
    49
    54
     0
    19
    19
    33
```
This appears to be number of characters of each line emitted by command `dotnet aws list-deployments --profile default --region us-east-1`.
