### ISSUE TITLE
Cannot deploy BlazorWasm application on M1 Mac

### ISSUE THREAD

**Issue by timmattison** [aws/aws-dotnet-deploy#719]
### Describe the bug

I can run `dotnet aws deploy` on my Intel Mac to deploy a BlazorWasm app to AWS and it works just fine but when I try to run `dotnet aws deploy` on my M1 Mac I get this error.

```
*************************
Deploying AWS CDK project
-------------------------
Use the CDK project to create or update the AWS CloudFormation stack and deploy the project to the AWS resources in the stack.
*************************

A fatal error occurred. The required library libhostfxr.dylib could not be found.
If this is a self-contained application, that library should exist in [/Users/timmattison/.aws-dotnet-deploy/Projects/2pw0ajvw/bin/Debug/netcoreapp3.1/].
If this is a framework-dependent application, install the runtime in the global location [/usr/local/share/dotnet/x64] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].

The .NET Core runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=osx.10.17-x64

Subprocess exited with error 131
```

Is there a fix for this? I've seen mentions of removing duplicate .NET SDKs but I only have one installed so I don't think that's the issue.

### Expected Behavior

I should be able to deploy my application from the command-line tool on an Intel Mac the same way I'd do it on an M1 Mac.

### Current Behavior

The Intel Mac works. The M1 Mac fails with the error above.

### Reproduction Steps

On an M1 Mac:

```
dotnet tool install -g aws.deploy.tools
mkdir temp
cd temp
dotnet new blazorwasm
dotnet aws deploy
```

After accepting the default values this process will fail on an M1 Mac.

### Possible Solution

Somewhere the code is making the assumption that it needs to use X64 resources. That's got to be changed but I have no idea where.

### Version used

1.5.4+c1bf3d17e4

### Operating System and version

Mac OS 12.6

**Comment by normj** [comment]
Can you clarify for me on your M1 if you have just the ARM version of .NET or both the ARM and X64 version of .NET installed. You can confirm that by looking in your `/usr/local/share/dotnet/` folder. If there is a sub folder from here called `x64` with a `dotnet` executable in it then you have both ARM and .NET installed. 

My theory is you don't have the `x64` emulation version which should be fine but since our CDK projects that the tool generates target .NET Core 3.1 that is requiring the `x64` emulation. We should probably think about updating the CDK generated projects to .NET 6 since that is what is needed for M1 without emulation plus .NET Core 3.1 goes out of support in December.

**Comment by timmattison** [comment]
I found a few `x64` directories:

```
% find /usr/local/share/dotnet -name "x64"
/usr/local/share/dotnet/sdk/6.0.300/x64
/usr/local/share/dotnet/sdk/6.0.300/TestHost/x64
```

**Comment by philasmar** [comment]
Starting version 1.8.8 https://github.com/aws/aws-dotnet-deploy/releases/tag/1.8.8 we no longer use netcoreapp3.1 for deployments we perform. The recipes are now using .NET 6 which supports ARM. Make sure you update your deploy tool version and make sure you have the ARM version of .NET 6 installed on your machine.
